### PR TITLE
Update readme

### LINKED ISSUE #53: Update the README for 3.2

### PR DESCRIPTION
**Pull request by ChrisMaddock**
Fixes #53.

This should be reviewed with the new docs -> https://github.com/nunit/docs/wiki/NUnit-Xamarin-Runners

The first page is the only new one there, the other two have essentially been copied out the old readme. On the new readme, I've aimed for 'friendly'! Can tone it down if we think it's too much! Also, I've linked to the framework Contributors.md for now...would like to generalise that and maybe move it to docs at some point...

Couple of queries:
- I'm a windows-man, but I'm led to believe Xamarin Studio has now essentially been re-skinned as Visual Studio for Mac, so I've renamed accordingly. Is that right?
- I corrected the docs from `nunit.Autorun = true` to the new `nunit.Options = new TestOptions...`. I guess this is a breaking change, d'ya think that's ok, or should we add back the `nunit.Autorun` as a property which can create `TestOptions`?

### CODE REVIEW

**Comment by ChrisMaddock** [comment]
It would be good to also add Gitter to this, if we think we're going to keep it!

**Comment by rprouse** [comment]
This looks good. I would like to add the Gitter badge to the various Readme pages, but let's hold off on that and discuss it as a team. I think it is working fairly well so far, but we should make a team decision on that.

**Comment by ChrisMaddock** [comment]
Sounds good. :-)

**Comment by ChrisMaddock** [comment]
@rprouse - what do you think to this? Leave it with the breaking change, and keep the internals clean?

> I corrected the docs from `nunit.Autorun = true` to the `new nunit.Options = new TestOptions{...}` I guess this is a breaking change, d'ya think that's ok, or should we add back the nunit.Autorun as a property which can create TestOptions?

**Comment by rprouse** [comment]
I am good with the breaking change for this one. It isn't widely used, it is a small upgrade step and it is documented.

**Pull request merged**
