### PR TITLE
Update to NUnit 3.6.1

### PR DESCRIPTION
**Pull request by ChrisMaddock**
I was going to do this with #75, but it changed so much I thought it was better separately. 😕 

This updates NUnit to 3.6 - which appears to have added netstandard 1.6 packages and a world of dependencies. I'm not sure why - it's referencing the version in MonoAndroid/MonoiOS, which I thought was still PCL? I've left it as NuGet did it so I'm not unwittingly breaking anything - but this isn't expected, is it?

It also updates Xamarin.Forms at the same time, just so it's released with the latest. That one was simple. I initially updated the android version too, but it appears the latest currently doesn't seem to build on Appveyor. There's a mass of issues with mscorlib references on all sorts of CI servers - so I'm hoping for a Xamarin/Appveyor fix later on instead...

### CODE REVIEW

**Comment by ChrisMaddock** [comment]
Need to put this on hold - the .NET Standard table I used to check what was going on here was out of date. Looks like iOS10 supports netstandard 1.6, and Android 7.1. That explains why the netstandard versions were pulled in. 

I retargetted back to Android 6 however, due to 7.1 it failing to build on Appveyor. Not sure why this still builds referencing the netstandard package - I wonder if it's actually referencing the PCL at compile time or something and the HintPaths are wrong.. 😕 I'll look in to it at some point.

**Comment by ChrisMaddock** [comment]
Well, this turned into a yak-shaver. Finally ready for review - I still don't have access to a Mac to build iOS, would you mind testing it out Rob?

Two issues to talk about:

1. .NET standard 
The projects reference the PCL builds (MonoAndroid/Xamarin.iOS10) - but by default, a packages.config project pulls in all the dependencies packages for the netstandard build. See: https://forums.xamarin.com/discussion/82753/adding-net-standard-nuget-package

To avoid adding 40 off unnecessary NuGet packages, I converted everything to project.json. (Thanks @twsouthwick for the great VSIX to automate that!)

One thought, if we re-target the framework PCL to netstandard 1.0, is that definitely consumable by older Xamarin projects? This was the most reliable compatibility table I could find - but documentation on Xamarin/netstandard is sparse!

|.NET Platform              | 1.0| 1.1| 1.2| 1.3| 1.4| 1.5| 1.6| 2.0|
|:--------------------------|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|
|.NET Core                  |&rarr;|&rarr;|&rarr;|&rarr;|&rarr;|&rarr;|   1.0| vNext|
|.NET Framework             |&rarr;|  4.5 | 4.5.1|   4.6|&rarr;|&rarr;|&rarr;| 4.6.1|
|Mono                       |&rarr;|&rarr;|&rarr;|&rarr;|&rarr;|&rarr;|   4.6| vNext|
|Xamarin.iOS                |&rarr;|&rarr;|&rarr;|&rarr;|&rarr;|&rarr;|  10.0| vNext|
|Xamarin.Android            |&rarr;|&rarr;|&rarr;|&rarr;|&rarr;|&rarr;|   7.0| vNext|
|Universal Windows Platform |&rarr;|&rarr;|&rarr;|&rarr;|  10.0|&rarr;|&rarr;| vNext|
|Windows                    |&rarr;|   8.0|   8.1|      |      |      |      |      |
|Windows Phone              |&rarr;|&rarr;|   8.1|      |      |      |      |      |
|Windows Phone Silverlight  |   8.0|      |      |      |      |      |      |      |

2. Android level
I initially tried to update to the latest Android 7.1, but Appveyor doesn't have the dependencies installed, and getting that together is a war I just don't want to wage right now. ;-) I filed an issue at https://github.com/appveyor/ci/issues/1280 which has been put on a milestone soonish, so I suggest we leave that one until Appveyor is updated.

Unfortunately - this had meant the 2.x version of Xamarin Forms I'd updated to previously would potentially fail at runtime as some of it's dependencies were targeted to Android 7.0. (See: https://forums.xamarin.com/discussion/44678/psa-you-must-set-your-target-compile-version-of-your-android-projects-to-latest) I've reverted to 1.5.x for now.

**Comment by rprouse** [comment]
This looks good, but I can't test on iOS right now either. I am travelling and won't have access to one of my Mac build machines until Tuesday.

**Comment by ChrisMaddock** [comment]
Rebasing has broken the build, but there's no reason in the logs. I'll have to pull it down and have a look...

**Comment by ChrisMaddock** [comment]
Fixed - just a reference that went missing during rebase. :-/

**Comment by rprouse** [comment]
👍

**Comment by ChrisMaddock** [comment]
Merged this so I can rebase the release over it. 

@plneto has tried the iOS build, and I checked Android and UWP, so fairly happy things are a-ok!

**Pull request merged**
