### PR TITLE
Prepare for 3.6.1 release

### PR DESCRIPTION
**Pull request by ChrisMaddock**
This is the release PR for 3.6.1. This replaces #90 - which was closed automatically when I renamed the branch.

@rprouse - There's a draft release in place. The only odd bit is that GitHub currently shows the git-tag and the draft release separately. I don't know if these will merge together automatically when the release is published, or if the release notes will need copying over.

Other than that, as far as I'm aware, the remaining things to do are:

- [ ] Review this PR/release package
- [ ] Make release public
- [ ] Push to NuGet
- [ ] Rebuild website
- [ ] Merge back to master. (I'm happy to do this one!)

Let me know if I've missed anything, or if there's any more I can do! 😄

### CODE REVIEW

**Comment by ChrisMaddock** [comment]
Note the master CI is currently failing at the packaging stage, as it takes the git-tag as the version. I kept this consistent with the other tags in this repo, using the format "v3.6.1" - but that isn't a valid NuGet version string.

The release package is built from the branch, so doesn't use the git-tag that's on the master. In future, perhaps we should tag as "3.6.1" without the "v"? That's how it is in the framework repository. Alternatively, we could adjust the Cake script to sanitise this.

**Comment by ChrisMaddock** [comment]
Thanks Rob.

The next steps are in your hands - I don't have the keys to upload to NuGet, or relaunch the website. If you can sort those two, I can merge back to master. 😄

**Comment by rprouse** [comment]
I am a bit delayed on this. Sat down to do it tonight and my computer booted to updating windows. Now my computer isn't booting...

**Comment by rprouse** [comment]
Well, windows update ended being a full OS reinstall. Working through it now, hopefully can test and release tomorrow.

**Comment by rprouse** [comment]
Thanks for your help on this @ChrisMaddock. It has been released.

**Comment by ChrisMaddock** [comment]
Great, thanks @rprouse! I'll do the merge back to master tonight. 😄

**Pull request merged**
